# Generated by Django 2.1.4 on 2018-12-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contant',
            new_name='Contact',
        ),
    ]
